# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_ar')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_ar')
    _ar = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_ar', [dirname(__file__)])
        except ImportError:
            import _ar
            return _ar
        try:
            _mod = imp.load_module('_ar', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _ar = swig_import_helper()
    del swig_import_helper
else:
    import _ar
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0


def cdata(ptr, nelements=1):
    return _ar.cdata(ptr, nelements)
cdata = _ar.cdata

def memmove(data, indata):
    return _ar.memmove(data, indata)
memmove = _ar.memmove
class float_array(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, float_array, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, float_array, name)
    __repr__ = _swig_repr

    def __init__(self, nelements):
        this = _ar.new_float_array(nelements)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this
    __swig_destroy__ = _ar.delete_float_array
    __del__ = lambda self: None

    def __getitem__(self, index):
        return _ar.float_array___getitem__(self, index)

    def __setitem__(self, index, value):
        return _ar.float_array___setitem__(self, index, value)

    def cast(self):
        return _ar.float_array_cast(self)
    if _newclass:
        frompointer = staticmethod(_ar.float_array_frompointer)
    else:
        frompointer = _ar.float_array_frompointer
float_array_swigregister = _ar.float_array_swigregister
float_array_swigregister(float_array)

def float_array_frompointer(t):
    return _ar.float_array_frompointer(t)
float_array_frompointer = _ar.float_array_frompointer


def AutoRegressionPy(inputseries, length, degree, coefficients, method):
    return _ar.AutoRegressionPy(inputseries, length, degree, coefficients, method)
AutoRegressionPy = _ar.AutoRegressionPy
# This file is compatible with both classic and new-style classes.


